FormKey: 05E71A:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12634
EditorID: MantellaNPCActionsSettings
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 5
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_05
    - FragmentIndex: 10
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_10
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_01
    - FragmentIndex: 4
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_04
    - FragmentIndex: 7
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_07
    - FragmentIndex: 9
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_09
    - FragmentIndex: 2
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_02
    - FragmentIndex: 6
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_06
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_03
    - FragmentIndex: 8
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaNPCActionsSetti_0705E71A
      FragmentName: Fragment_Terminal_08
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - NPC Actions Settings (Experimental)
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Event Tracking Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: >-
      Choose an option. 

      NPC Aggro : NPCs will turn hostile when they receive insults. If the offender asks for forgiveness they will stop combat. (this function does not work on followers and settlers)

      NPC Follow : NPCs will become teamates when given a reason to do so. (may not work on every NPC)

      NPC stay in place : NPCs will stay in place during a Mantella conversation. Companions will still follow the player but will not sandbox.
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Turn NPC aggro OFF
  Type: DisplayText
  ItemId: 3
  DisplayText:
    TargetLanguage: English
    Value: NPC aggro is turned OFF
  Conditions:
  - MutagenObjectType: ConditionFloat
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3EA8:Mantella.esp
      ParameterTwoNumber: 785268392
      ParameterTwoString: ::allowActionAggro_var
- ItemText:
    TargetLanguage: English
    Value: Turn NPC aggro ON
  Type: DisplayText
  ItemId: 1
  DisplayText:
    TargetLanguage: English
    Value: NPC aggro is turned ON. Make sure your Fallout 4 prompt in the Mantella config.ini has the 'Offended:' and 'Forgiven:'   instructions enabled (remove the semi-colon in front of the line to enable the instruction).
  Conditions:
  - MutagenObjectType: ConditionFloat
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3EA0:Mantella.esp
      ParameterTwoNumber: 785268384
      ParameterTwoString: ::allowActionAggro_var
- ItemText:
    TargetLanguage: English
    Value: Turn NPC follow OFF
  Type: DisplayText
  ItemId: 2
  DisplayText:
    TargetLanguage: English
    Value: NPC follow is turned OFF
  Conditions:
  - MutagenObjectType: ConditionFloat
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E98:Mantella.esp
      ParameterTwoNumber: 785268376
      ParameterTwoString: ::allowFollow_var
- ItemText:
    TargetLanguage: English
    Value: Turn NPC follow ON
  Type: DisplayText
  ItemId: 4
  DisplayText:
    TargetLanguage: English
    Value: NPC follow is turned ON. (Implies Stay in place) Make sure your Fallout 4 prompt in the Mantella config.ini has the 'Follow:'  instruction enabled (remove the semi-colon in front of the line to enable the instruction).
  Conditions:
  - MutagenObjectType: ConditionFloat
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E90:Mantella.esp
      ParameterTwoNumber: 785268368
      ParameterTwoString: ::allowFollow_var
- ItemText:
    TargetLanguage: English
    Value: Turn NPC stay in place OFF
  Type: DisplayText
  ItemId: 5
  DisplayText:
    TargetLanguage: English
    Value: NPCs will continue their current routine during a Mantella conversation. Companions will be allowed to sandbox during a Mantella conversation.
  Conditions:
  - MutagenObjectType: ConditionFloat
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E88:Mantella.esp
      ParameterTwoNumber: 785268360
      ParameterTwoString: ::allowNPCsStayInPlace_var
- ItemText:
    TargetLanguage: English
    Value: Turn NPC stay in place ON
  Type: DisplayText
  ItemId: 6
  DisplayText:
    TargetLanguage: English
    Value: NPCs will stay in place during a Mantella conversation. Companions will still follow the player but will not sandbox.
  Conditions:
  - MutagenObjectType: ConditionFloat
    CompareOperator: NotEqualTo
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E80:Mantella.esp
      ParameterTwoNumber: 785268352
      ParameterTwoString: ::allowNPCsStayInPlace_var
- ItemText:
    TargetLanguage: English
    Value: Turn Allow NPC OpenInventory OFF
  Type: DisplayText
  ItemId: 7
  DisplayText:
    TargetLanguage: English
    Value: NPCs will not open their inventories anymore when requested to through Mantella.
  Conditions:
  - MutagenObjectType: ConditionFloat
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E78:Mantella.esp
      ParameterTwoNumber: 785268344
      ParameterTwoString: ::allowActionInventory_var
- ItemText:
    TargetLanguage: English
    Value: Turn Allow NPC OpenInventory ON
  Type: DisplayText
  ItemId: 8
  DisplayText:
    TargetLanguage: English
    Value: >+
      NPCs will now open their inventories when requested to through Mantella. Make sure the Fallout4 prompt in the Mantella config includes the relevant instruction. See below : 


      To show the player what you have in your inventory or to give / take an item, begin your response with 'Inventory:'.
  Conditions:
  - MutagenObjectType: ConditionFloat
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E70:Mantella.esp
      ParameterTwoNumber: 785268336
      ParameterTwoString: ::allowActionInventory_var
- ItemText:
    TargetLanguage: English
    Value: Turn Allow NPC Function Calling OFF
  Type: DisplayText
  ItemId: 9
  DisplayText:
    TargetLanguage: English
    Value: 'NPC Function Calling is turned OFF. NPC will now take dynamic actions through Mantella (warning: this will increase token use on your LLM service)'
  Conditions:
  - MutagenObjectType: ConditionFloat
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E68:Mantella.esp
      ParameterTwoNumber: 785268328
      ParameterTwoString: ::allowFunctionCalling_var
- ItemText:
    TargetLanguage: English
    Value: Turn Allow NPC Function Calling ON
  Type: DisplayText
  ItemId: 10
  DisplayText:
    TargetLanguage: English
    Value: NPC Function Calling is turned ON.
  Conditions:
  - MutagenObjectType: ConditionFloat
    Data:
      MutagenObjectType: FunctionConditionData
      Function: GetVMQuestVariable
      ParameterOneRecord: 000F99:Mantella.esp
      ParameterOneNumber: 16781209
      ParameterTwoRecord: CE3E60:Mantella.esp
      ParameterTwoNumber: 785268320
      ParameterTwoString: ::allowFunctionCalling_var
MajorFlags:
- 0x10
- 0x2000
